version: '3'

services:

  hassio:
    image: homeassistant/armhf-hassio-supervisor
    container_name: hassio_supervisor
    privileged: true
    entrypoint: ["/bin/bash", "-c", "/data/hassio.sh"]
    security_opt:
      - seccomp:unconfined
    environment:
      - HOMEASSISTANT_REPOSITORY=homeassistant/raspberrypi4-homeassistant
      #@TODO - avoid hardcoding share absolute path
      - SUPERVISOR_SHARE=/home/sergiu/hassio/data
      - SUPERVISOR_NAME=hassio_supervisor
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    healthcheck:
      test: ["CMD", "curl", "-sI", "http://127.0.0.1:8086/ping"]
      interval: 30s
      timeout: 1s
      retries: 24
    environment:
      - TZ=Europe/Bucharest
    ports:
      - 8083:8083
      - 8086:8086
    restart: on-failure
    volumes:
      - ./influxdb:/var/lib/influxdb


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - influxdb
    environment:
      - TZ=Europe/Bucharest
      - PGID=1000
      - PUID=1000
    ports:
      - 3000:3000
    user: root
    restart: on-failure
    volumes:
      - ./grafana:/var/lib/grafana


  mariadb:
    image: linuxserver/mariadb:latest
    container_name: mariadb
    environment:
       - MYSQL_ROOT_PASSWORD=mysecretpass
       - MYSQL_DATABASE=home_assistant
       - MYSQL_USER=hassio
       - MYSQL_PASSWORD=othersecretpass
    ports:
       - 3306:3306
    user: root
    privileged: true
    volumes:
       - ./mysql:/var/lib/mysql
